title: "[Question] "
labels: []
body:
- type: markdown
  attributes:
    value: Some text that shows up in the template
- type: textarea
  attributes:
    label: Question
    description: |
      State your question. Be as specific as possible.
  validations:
    required: true
- type: textarea
  attributes:
    label: Context
    description: Pelase provide some context for your question that could be useful to someone trying to answer it.
  validations:
    required: true
